version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"                # Location of go.mod
    schedule:
      interval: "weekly"          # Options: daily, weekly, monthly
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      include: "scope"
    assignees:
      - "jclement"    
    labels:
      - "dependencies"
