services:
  sync:
    image: ghcr.io/afenav/execute-sync:${TAG:-latest}
    env_file:
      - .env
    volumes:
      - syncstate:/var/run/execute-sync
    restart: unless-stopped
volumes:
  syncstate:
