services:
  sync:
    image: ghcr.io/afenav/execute-sync:${TAG:-latest}
    environment:
      - EXECUTESYNC_DATABASE_TYPE=${EXECUTESYNC_DATABASE_TYPE}
      - EXECUTESYNC_DATABASE_DSN=${EXECUTESYNC_DATABASE_DSN}
      - EXECUTESYNC_EXECUTE_URL=${EXECUTESYNC_EXECUTE_URL}
      - EXECUTESYNC_EXECUTE_APIKEY_ID=${EXECUTESYNC_EXECUTE_APIKEY_ID}
      - EXECUTESYNC_EXECUTE_APIKEY_SECRET=${EXECUTESYNC_EXECUTE_APIKEY_SECRET}
      - EXECUTESYNC_WAIT=${EXECUTESYNC_WAIT:-600}
    env_file:
      - .env
    volumes:
      - syncstate:/var/run/execute-sync
    restart: unless-stopped
volumes:
  syncstate:
